name: az-ml-realtime-score
channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - pip
  - jupyter
  - pytest
  - pytest-cov
  - pylint
  - pandas
  - pip:
    - papermill
    - azureml-core==1.0.85.2
    - pylint-junit
    - pytest-nunit
    - nbconvert
    - junit-xml
    - nbformat
    - Microsoft-AI-Azure-Utility-Samples==0.2.3
    - python-dotenv
