name: ai-architecture-template
channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - pip
  - jupyter
  - pytest
  - pytest-cov
  - pylint
  - pip:
    - papermill
    - azureml-core
    - pylint-junit
    - pytest-nunit
    - nbconvert
    - junit-xml
    - Microsoft-AI-Azure-Utility-Samples==0.2.2
