# MLAKSDeploy Pipeline
resources:
  repositories:
    - repository: aitemplates
      type: github
      name: microsoft/AI
      endpoint: AIArchitecturesAndPractices-GitHub

variables:
  BuildConfiguration: Release
  BuildBinariesDirectory: $(Build.BinariesDirectory)
  BuildPlatform: any cpu
  DotNetCoreBuildVersion: 2.2.108
  DotNetRuntimeTarget: ubuntu.18.04-x64
  AgentToolsDirectory: $(Agent.ToolsDirectory)
  CloudPlatform: AzureCloud
  ProductName: Trident
  TridentWorkloadType: $(WorkloadType)
  TridentWorkloadTypeShort: $(WorkloadTypeShort)
  DeployLocations: eastus
  Agent: agce-ai
  azureSubscription: AG-AzureCAT-AIDevOps-Test-COGSNonProd-IO1685734(0ca618d2-22a8-413a-96d0-0f1b531129c3)
  azure_subscription: 0ca618d2-22a8-413a-96d0-0f1b531129c3

trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: build_deploy_ai
  displayName: 'Build deploy AI'

  strategy:
    maxParallel: 8
    matrix: $[ dependencies.build_relayer_sources.outputs['GenDeployMatrix.DeployRegions'] ]
  timeoutInMinutes: 180

  workspace:
    clean: all

  variables:
    DeploymentGuidTag: $[ dependencies.build_relayer_sources.outputs['GenDeployGuidTag.DeploymentGuid'] ]
    DeploymentTimeStamp: $[ dependencies.build_relayer_sources.outputs['GenDeployTimeStamp.timeStamp'] ]
    EnvironmentPrefix: $(TridentWorkloadType)-$(CloudPlatform)-$(DeployLocation)$(TestPostfix)
    ResourcePrefix: $(TridentWorkloadTypeShort)-$(DeployLocation)$(TestPostfix)
    EnvironmentContext: $(EnvironmentPrefix)-$(DeploymentGuidTag)
    AIResourceGroupName: $(TridentWorkloadTypeShort)-$(DeployLocation)$(TestPostfix)

  steps:

  #
  # ML RTS - Workload Deployment
  #
    # use the ML team templates to build and deploy workloads for each region
  - script: |
      docker stop $(docker ps -a -q)
      docker rm $(docker ps -a -q)
      docker system prune -a -f
      rm -rf AI
      git clone --recurse-submodules https://github.com/microsoft/AI.git
    displayName: 'git clone sources'

  - bash: |
      Deploy_Location_Short=$(echo $DeployLocation | cut -c1-12)
      echo "##vso[task.setvariable variable=Deploy_Location_Short]$Deploy_Location_Short"


  - template: .ci/steps/deploy_steps.yml@aitemplates
    parameters:
      deployment_name: MLBatchDeployAMLJob
      template: MLBatchDeployAMLJob.yml
      azureSubscription: $(azureSubscription)
      azure_subscription: $(azure_subscription)
      azureresourcegroup: $(AIResourceGroupName)
      workspacename: $(TridentWorkloadTypeShort)-$(DeployLocation)
      azureregion: $(DeployLocation)
      aksimagename: myimage
      environment: $(EnvironmentContext)
      doCleanup: False
      alias: $(Build.QueuedBy)
      project: $(TridentWorkloadTypeShort)
      agent: "Hosted Ubuntu 1604"
      ENVIRONMENT_PREFIX: $(EnvironmentPrefix)
      deploymentguidtag: $(DeploymentGuidTag)
      aks_name: $(TridentWorkloadTypeShort)$(Deploy_Location_Short)
      python_path: "$(System.DefaultWorkingDirectory)/AI/submodules/DeployMLModelPipelines"
      location: AI/submodules/DeployMLModelPipelines
      python_secret_root: "./AI/"
