name: MLAKSDeployAML
channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - pip=19.3.1
  - tornado<6
  - nb_conda_kernels
  - ipywidgets
  - pandas
  - scikit-learn
  - urllib3
  - pip:    
    - aiohttp
    - nest_asyncio
    - toolz
    - tqdm
    - azure-cli
    - prompt_toolkit
    - lightgbm
    - papermill
    - python-dotenv
    - azureml-sdk[notebooks]==1.0.57
    - azure-core
    - locustio
    - git+https://github.com/microsoft/AI-Utilities.git    
